toko-online/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();
Route::match(["GET","POST"],"/register",function(){
    return redirect('/login');
})->name('register');


#Dashboard
Route::get('/home', 'HomeController@index')->name('home');


Route::resource('/users','UserController')->middleware('auth');
Route::resource('/categories','CategoryController')->middleware('auth');;

toko-online/app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    //
}

toko-online/app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use Illuminate\Http\Request;
use DB;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $categories=\App\Category::paginate(2);
        $filterkeyword=$request->get('name');

        if($filterkeyword){
            $categories=\App\Category::where('name','LIKE',"%$filterkeyword%")->paginate(10);
        }
        return view('categories.index',['categories'=>$categories]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('categories.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $name=$request->get('name');

        $new_category= new \App\Category;
        $new_category->name=$name;
        if($request->file('image')){
            $image_path=$request->file('image')->store('category_images','public');
            $new_category->image=$image_path;
        }
        $new_category->created_by = \Auth::user()->id;
        $new_category->slug = \Str::slug($name, '-');
        $new_category->save();
        
        return redirect()->route('categories.create')->with('status','Category successfully created');

    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function show(Category $category)
    {
        $category=\App\Category::findOrFail($id);
        return view('categories.show',['kategori'=>$category]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $category_edit=\App\Category::findOrFail($id);
        return view('categories.edit',['category'=>$category_edit]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Category $category)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function destroy(Category $category)
    {
        //
    }
}

toko-online/resources/views/categories/create.blade.php
@extends('layouts.global')

@section('title') Create Kategori
@endsection

@section('content')

<div class="col-md-8">
    @if(session('status'))
    <div class="alert alert-success">
        {{session('status')}}
    </div>
    @endif

    <form enctype="multipart/form-data" class="bg-white shadow-sm p-3" action="{{route('categories.store')}}" method="POST">
        @csrf
        <label>Category name</label><br>
        <input type="text" class="form-control" name="name" />
        <br>
        <label>Category image</label>
        <input type="file" class="form-control" name="image" />
        <br>
        <input type="submit" class="btn btn-primary" value="Save" />
    </form>
</div>
@endsection

toko-online/resources/views/categories/edit.blade.php
@extends('layouts.global')

@section('title') Edit Category
@endsection

@section('content')
<div class="col-md-8">
<form
    action="{{route('categories.update', [$category->id])}}" enctype="multipart/form-data" method="POST"
    class="bg-white shadow-sm p-3">
@csrf
<input type="hidden" value="PUT" name="_method">
</form>
</div>
@endsection

toko-online/resources/views/categories/index.blade.php
@extends('layouts.global')

@section('title') Kategori
@endsection

@section('content')

<h4>List Category</h4>
<div class="row">
    <div class="col-md-6">
        <form action="{{route('categories.index')}}">
            <div class="input-group">
                <input type="text" class="form-control" placeholder="Filter by category name" name="name">
                    <div class="input-group-append">
                    <input type="submit" value="Filter" class="btn btn-primary">
                </div>
            </div>
        </form>
    </div>
<hr class="my-4">

    <div class="col-md-12">
        <table class="table table-bordered table-stripped">
            <thead>
                <tr>
                    <th><b>Name</b></th>
                    <th><b>Slug</b></th>
                    <th><b>Image</b></th>
                    <th><b>Actions</b></th>
                </tr>
            </thead>
            <tbody>
                @foreach ($categories as $category)
                <tr>
                    <td>{{$category->name}}</td>
                    <td>{{$category->slug}}</td>
                    <td>
                        @if($category->image)
                        <img src="{{asset('storage/' . $category->image)}}" width="48px" />
                        @else
                        No image
                        @endif
                    </td>
                    <td>
                        {{-- Edit  --}}
                        <a class="btn btn-info text-white btn-sm" href="{{route('categories.edit',[$category->id]) }}">Edit</a>
                        @if (session('status'))
                        <div class="alert alert-success">
                            {{ session('status') }}
                        </div>
                        @endif

                        {{-- Detail --}}
                        <a href="{{route('categories.show',[$category->id]) }}" class="btn btn-primary btn-sm">Detail</a>

                        {{-- Delete --}}
                        <form onsubmit="return confirm('Delete this user permanently?')" class="d-inline" action="{{route('categories.destroy', [$category->id])}}" method="POST">
                            @csrf
                            <input type="hidden" name="_method" value="DELETE">
                            <input type="submit" value="Delete" class="btn btn-danger btn-sm">
                        </form>
                    </td>
                </tr>
                @endforeach
            </tbody>
            <tfoot>
                <tr>
                    <td colSpan="2">
                        {{$categories->appends(Request::all())->links()}}
                    </td>
                </tr>
            </tfoot>
        </table>
    </div>
</div>

@endsection

toko-online/resources/views/categories/show.blade.php
@extends('layouts.global')

@section('title') Show Category
@endsection

@section('content')

@endsection