toko-online/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();
Route::match(["GET","POST"],"/register",function(){
    return redirect('/login');
})->name('register');


#Dashboard
Route::get('/home', 'HomeController@index')->name('home');


Route::resource('/users','UserController')->middleware('auth');
Route::resource('/categories','CategoryController')->middleware('auth');;

toko-online/app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;
    use HashRoles;
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'username','name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

toko-online/app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\User;
use DB;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $status=$request->get('status');
        $users=\App\User::paginate(2);
        $filterKeyword=$request->get('keyword');


        if($filterKeyword){
            if($status){
                $users=\App\User::where('name','LIKE',"%$filterKeyword%")
                ->where('status',$status)
                ->paginate(2);
            }else{
                $users=\App\User::where('name','LIKE',"%$filterKeyword%")
                ->paginate(2);
            }
         
        }

        // #variabel $user untuk di lempar ke index.blade.php
        return view('users.index',['users'=>$users]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('users.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $new_user = new \App\User;
        $new_user->name = $request->get('name');
        $new_user->username = $request->get('username');
        $new_user->roles = json_encode($request->get('roles'));
        $new_user->address = $request->get('address');
        $new_user->phone = $request->get('phone');
        $new_user->email = $request->get('email');
        $new_user->password = \Hash::make($request->get('password'));
        if($request->file('avatar')){
            $file = $request->file('avatar')->store('avatars', 'public');
            $new_user->avatar = $file;
            }
            $new_user->save();
        return redirect()->route('users.create')->with('status', 'User successfully created');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $user=\App\User::findOrFail($id);
        return view('users.show',['user'=>$user]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user=\App\User::findOrFail($id);
        return view('users.edit',['user'=>$user]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $user=\App\User::findOrFail($id);
        $user->name=$request->get('name');
        $user->roles=json_encode($request->get('roles'));
        $user->address=$request->get('address');
        $user->phone=$request->get('phone');
        $user->status=$request->get('status');

        if($request->file('avatar')){
            if($user->avatar && file_exists(storage_path('app/public/'.$user->avatar))){\Storage::delete('public/'.$user->avatar);
            }
            $file=$request->file('avatar')->store('avatars','public');
            $user->avatar=$file;
        }
        $user->save();
        return redirect()->route('users.edit',[$id])->with('status','User Succesfully Update');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $user=\App\User::findOrFail($id);
        $user->delete();
        return redirect()->route('users.index')->with('status','User succesfully delete');
    }
    
}

toko-online/resources/views/users/create.blade.php
@extends('layouts.global')

@section('title')Create User @endsection

@section('content')
<div class="col-md-8">

    @if(session('status'))
    <div class="alert alert-success">
        {{session('status')}}
    </div>
    @endif

    <form enctype="multipart/form-data" class="bg-white shadow-sm p-3" action="{{route('users.store')}}" method="POST">
        @csrf
        <label for="name">Name</label>
        <input class="form-control" placeholder="Full Name" type="text" name="name" id="name" required/>
        <br>
        <label for="username">Username</label>
        <input class="form-control" placeholder="username" type="text" name="username" id="username" required />
        <br>
        <label for="">Roles</label>
        <br>
        <input type="checkbox" name="roles[]" id="ADMIN" value="ADMIN" >
        <label for="ADMIN">Administrator</label>
        <input type="checkbox" name="roles[]" id="STAFF" value="STAFF">
        <label for="STAFF">Staff</label>
        <input type="checkbox" name="roles[]" id="CUSTOMER" value="CUSTOMER" >
        <label for="CUSTOMER">Customer</label>
        <br>
        <br>
        <label for="phone">Phone number</label>
        <br>
        <input type="text" name="phone" class="form-control" required>
        <br>
        <label for="address">Address</label>
        <textarea name="address" id="address" class="form-control" required></textarea>
        <br>
        <label for="avatar">Avatar image</label>
        <br>
        <input id="avatar" name="avatar" type="file" class="form-control" required>
        <hr class="my-3">
        <label for="email">Email</label>
        <input class="form-control" placeholder="user@mail.com" type="text" name="email" id="email" required/>
        <br>
        <label for="password">Password</label>
        <input class="form-control" placeholder="password" type="password" name="password" id="password" required />
        <br>

        <label for="password_confirmation">Password Confirmation</label>
        <input class="form-control" placeholder="password confirmation" type="password" name="password_confirmation" id="password_confirmation" required />
        <br>
        <input class="btn btn-primary" type="submit" value="Save" />
    </form>
</div>

@endsection

toko-online/resources/views/users/edit.blade.php
@extends('layouts.global')

@section('title') Edit User @endsection

@section('content')


{{-- {{ $user->email }} --}}

<div class="col-md-8">
    @if(session('status'))
    <div class="alert alert-success" role="alert">
        {{ session('status') }}
    </div>
    @endif

    <form enctype="multipart/form-data" class="bg-white shadow-sm p-3" action="{{route('users.update',[$user->id])}}" method="POST">
        @csrf
        <input type="hidden" value="PUT" name="_method">

        <label for="name">Name</label>
        <input value="{{ $user->name }}" type="text" name="name" class="form-control" placeholder="Full Name" id="name" /><br>

        <label for="username">Username</label>
        <input value="{{ $user->username }}" disable class="form-control" placeholder="username" type="text" name="username" id="username" />

        <br>
        <label for="">Status</label></br>

        <input {{ $user->status=="ACTIVE" ? "checked" : "" }} value="ACTIVE" type="radio" class="form-control" id="active" name="status">

        <label for="active">Active</label>
        <input {{ $user->status=="INACTIVE" ? "checked" : "" }} value="inactive" type="radio" class="form-control" id="inactive" name="status">

        <label for="inactive">Inactive</label>
        <br><br>
        <label for="">Roles</label>
        <br>
        <input type="checkbox" {{in_array("ADMIN",json_decode($user->roles))? "checked":"" }} name="roles[]" id="ADMIN" value="ADMIN">

        <label for="ADMIN">Administrator</label>
        <input type="checkbox" {{in_array("STAFF", json_decode($user->roles)) ?
        "checked" : ""}} name="roles[]" id="STAFF" value="STAFF">
        <label for="STAFF">Staff</label>
        <input type="checkbox" {{in_array("CUSTOMER", json_decode($user->roles)) ? "checked" : ""}} name="roles[]" id="CUSTOMER" value="CUSTOMER">
        <label for="CUSTOMER">Customer</label>
        <br>
        <br>
        <label for="phone">Phone number</label>
        <br>
        <input type="text" name="phone" class="form-control" value="{{$user->phone}}">
        <br>
        <label for="address">Address</label>
        <textarea name="address" id="address" class="form-control">{{$user->address}}
        </textarea>
        <br>
        <label for="avatar">Avatar image</label>
        <br>
        Current Avatar: <br>
        @if ($user->avatar)
        <img src="{{asset('storage/',$user->avatar) }}" width="100px" /><br>
        @else
        No Avatar
        @endif
        <br>
        <input id="avatar" name="avatar" type="file" class="form-control">
        <small class="text-muted">Kosongkan jika tidak ingin mengubah avatar</small>
        <hr class="my-3">

        <label for="email">Email</label>
        <input value="{{$user->email}}" disabled class="form-control" placeholder="user@mail.com" type="text" name="email" id="email" /><br>
        <input class="btn btn-primary" type="submit" value="Save" />
    </form>
</div>
@endsection

toko-online/resources/views/users/index.blade.php
@extends('layouts.global')

@section('title') List User @endsection

@section('content')

<h4>Daftar User List</h4>
<div class="row mt-2">
    <div class="col-md-6">



        <form action="{{route('users.index')}}">
            <div class="row">
                <div class="col-md-6">
                    <input value="{{Request::get('keyword')}}" name="keyword" class="form-control" type="text" placeholder="Masukan nama untuk filter..." />
                </div>
                <div class="col-md-6">
                    <input {{Request::get('status') == 'ACTIVE' ? 'checked' : ''}} value="ACTIVE" name="status" type="radio" class="form-control" id="active">
                    <label for="active">Active</label>

                    <input {{Request::get('status') == 'INACTIVE' ? 'checked' : ''}} value="INACTIVE" name="status" type="radio" class="form-control" id="inactive">
                    <label for="inactive">Inactive</label>
                    <input type="submit" value="Filter" class="btn btn-primary">
                </div>
            </div>
        </form>
    </div>
</div>
{{-- Searching List --}}
<div class="row">
    <div class="col-md-12 text-right">
        <a href="{{route('users.create')}}" class="btn btn-primary">Create user <span class="oi oi-plus"></span></a>
    </div>
</div>
<br>

{{-- Tabel kedua --}}
<table class="col-md-7 table table-bordered ">
    <thead>
        <tr>

            <th><b>Name</b></th>
            <th><b>Username</b></th>
            <th><b>Email</b></th>
            <th><b>Avatar</b></th>
            <th><b>Status</b></th>
            <th><b>Action</b></th>

        </tr>
    </thead>
    <tbody>
        @foreach ( $users as $user )
        <tr>
            <td>{{ $user->name }}</td>
            <td>{{ $user->username }}</td>
            <td>{{ $user->email }}</td>

            <td>
                @if($user->avatar)
                <img src="{{ asset('storage/'.$user->avatar) }}" width="70px" />
                @else
                N/A
                @endif
            </td>
            <td>
                @if($user->status == "ACTIVE")
                <span class="badge badge-success">
                    {{$user->status}}
                </span>
                @else
                <span class="badge badge-danger">
                    {{$user->status}}
                </span>
                @endif
            </td>

            <td>
                {{-- Edit  --}}
                <a class="btn btn-info text-white btn-sm" href="{{route('users.edit',[$user->id]) }}">Edit</a>
                @if (session('status'))
                <div class="alert alert-success">
                    {{ session('status') }}
                </div>
                @endif

                {{-- Detail --}}
                <a href="{{route('users.show',[$user->id]) }}" class="btn btn-primary btn-sm">Detail</a>

                {{-- Delete --}}
                <form onsubmit="return confirm('Delete this user permanently?')" class="d-inline" action="{{route('users.destroy', [$user->id])}}" method="POST">
                    @csrf
                    <input type="hidden" name="_method" value="DELETE">
                    <input type="submit" value="Delete" class="btn btn-danger btn-sm">
                </form>
            </td>
        </tr>
        @endforeach
    </tbody>
    <tfoot>
        <tr>
            <td colspan=10>
                {{$users->appends(Request::all())->links()}}
            </td>
        </tr>
    </tfoot>
</table>
@endsection

toko-online/resources/views/users/show.blade.php
@extends('layouts.global')

@section('title') Detail User
@endsection

@section( 'content')

<div class="col-md-8">
    <div class="card">
        <div class="card-body">
            <b>Name:</b> <br />
            {{$user->name}}
            <br><br>

            @if($user->avatar)
            <img src="{{asset('storage/'. $user->avatar)}}" width="128px" />
            @else
            No avatar
            @endif

            <br>
            <br>
            <b>Username:</b><br>
            {{$user->email}}

            <br>
            <br>
            <b>Phone number</b> <br>
            {{$user->phone}}
            <br><br>
            <b>Address</b> <br>
            {{$user->address}}
            <br>
            <br>
            <b>Roles:</b> <br>
            @foreach (json_decode($user->roles) as $role)
            &middot; {{$role}} <br>
            @endforeach

            @endsection